#!/usr/bin/env python3
#

import os, sys, re, argparse
import numpy as np
from scipy.spatial.distance import cdist

# Ion residue names supported by all GroScore force fields
ION_RESIDUES = {"ZN", "CA", "MG", "CU", "CU1", "NA", "CL"}

#------------------------------------------------------

parser = argparse.ArgumentParser(description="Cut-out protein around the interface.")
parser.add_argument('-m','--chainmap', type=str, required=True, help="Chain map file containing residue numbers for protein B.")
args=parser.parse_args()

#------------------------------------------------------

def read_chain_map(filepath):
  """Read chain_map.gs file and return set of residue numbers belonging to protein B."""
  residues_b = set()
  if os.path.isfile(filepath):
    with open(filepath, "r") as f:
      for line in f:
        if not line.strip().startswith("#"):
          try:
            residues_b.add(int(line.strip()))
          except (ValueError, IndexError):
            pass
  return residues_b

residues_b = read_chain_map(args.chainmap)

#------------------------------------------------------

def read_ter_positions(filepath):
  """Read TER record positions from PDB file to preserve chain breaks.

  Tracks the residue BEFORE each TER record, as TER records may not include
  residue information (e.g., in files generated by cap_termini.py).

  Also identifies "real chain breaks" where the TER is between consecutively
  numbered residues. These represent true physical breaks (placed by
  renumber_pdb.py) and must never be removed, unlike gap-based TERs which
  can be cleaned up if the gap is later closed by fragment extension.

  Returns:
    ter_positions: set of (resnum, resname) tuples for all TER positions
    real_chain_breaks: set of (resnum, resname) tuples for TER positions
      between consecutively numbered residues
  """
  ter_positions = set()
  real_chain_breaks = set()
  if os.path.isfile(filepath):
    with open(filepath, "r") as f:
      prev_resnum = None
      prev_resname = None
      ter_before = None  # (resnum, resname) of residue before pending TER
      for line in f:
        if line.startswith("ATOM"):
          try:
            resnum = int(line[22:26].strip())
            resname = line[17:20].strip()
            # If we just passed a TER, check if next residue is consecutive
            if ter_before is not None:
              if resnum == ter_before[0] + 1:
                real_chain_breaks.add(ter_before)
              ter_before = None
            prev_resnum = resnum
            prev_resname = resname
          except (ValueError, IndexError):
            pass
        elif line.startswith("TER"):
          if prev_resnum is not None and prev_resname is not None:
            ter_positions.add((prev_resnum, prev_resname))
            ter_before = (prev_resnum, prev_resname)
  return ter_positions, real_chain_breaks

# Read TER positions from fixed_capped.pdb (or fixed.pdb if caps not used)
# This ensures TER positions match the residue numbering in conf.gro
if os.path.isfile("fixed_capped.pdb"):
  ter_positions, real_chain_breaks = read_ter_positions("fixed_capped.pdb")
else:
  ter_positions, real_chain_breaks = read_ter_positions("fixed.pdb")

#------------------------------------------------------

# cutoff parameters
interfacecutoff = 0.6
keepcutoff = 2.0
en_min = 0.4
en_max = 0.9

# read coordinate file - separate string and numeric data for efficiency
# Lists for string data (residue name, atom name)
prot1_resname = []
prot1_atomname = []
prot2_resname = []
prot2_atomname = []

# Lists for coordinates (will convert to numpy array)
prot1_coords = []
prot2_coords = []

if os.path.isfile("conf.gro"):
  with open("conf.gro", "r") as f:
    for line in f:
      if not line.strip().startswith("#"):
        left = line[:15]
        right = line[15:]
        tmp = left.split() + right.split()
        try:
          s = re.search(r"\d+(\.\d+)?", tmp[0])
          resnum = int(s.group(0))
          atomname = tmp[1]
          # Skip H* (hydrogens for distance calculations)
          if atomname[0] == "H":
            continue
          coords = [float(tmp[3]), float(tmp[4]), float(tmp[5])]
          if resnum not in residues_b:
            prot1_resname.append(tmp[0])
            prot1_atomname.append(atomname)
            prot1_coords.append(coords)
          else:
            prot2_resname.append(tmp[0])
            prot2_atomname.append(atomname)
            prot2_coords.append(coords)
        except (ValueError, IndexError, AttributeError):
          pass

# Convert to numpy arrays
prot1_coords = np.array(prot1_coords, dtype=np.float64)
prot2_coords = np.array(prot2_coords, dtype=np.float64)
len1 = len(prot1_resname)
len2 = len(prot2_resname)

if len1 == 0 or len2 == 0:
  # No atoms in one or both proteins - write empty file
  open("cutout.pdb", "w").close()
  sys.exit(0)

# Calculate all inter-protein distances at once using cdist
# This replaces the O(n*m) nested loop with a single vectorized call
all_distances = cdist(prot1_coords, prot2_coords)

# Find interface atom pairs (distance <= interfacecutoff)
interface_mask = all_distances <= interfacecutoff
interface_pairs = np.argwhere(interface_mask)

if len(interface_pairs) == 0:
  # No interface found
  open("cutout.pdb", "w").close()
  sys.exit(0)

# Get unique interface atom indices for each protein
interface_atoms1 = np.unique(interface_pairs[:, 0])
interface_atoms2 = np.unique(interface_pairs[:, 1])

# Find atoms within keepcutoff of interface atoms
# For prot1: calculate distances from all prot1 atoms to prot1 interface atoms
dist_to_interface1 = cdist(prot1_coords, prot1_coords[interface_atoms1])
keep1_mask = np.any(dist_to_interface1 <= keepcutoff, axis=1)
keep1_indices = np.where(keep1_mask)[0]
keep1_resnames = set(prot1_resname[i] for i in keep1_indices)

# For prot2: calculate distances from all prot2 atoms to prot2 interface atoms
dist_to_interface2 = cdist(prot2_coords, prot2_coords[interface_atoms2])
keep2_mask = np.any(dist_to_interface2 <= keepcutoff, axis=1)
keep2_indices = np.where(keep2_mask)[0]
keep2_resnames = set(prot2_resname[i] for i in keep2_indices)

# Get CA atoms from kept residues for elastic network check
protkeep1_indices = [i for i in range(len1) if prot1_resname[i] in keep1_resnames and prot1_atomname[i] == "CA"]
protkeep2_indices = [i for i in range(len2) if prot2_resname[i] in keep2_resnames and prot2_atomname[i] == "CA"]

# Check elastic network distances for CA atoms
laterkeep1_resnames = set()
if len(protkeep1_indices) > 1:
  ca_coords1 = prot1_coords[protkeep1_indices]
  ca_distances1 = cdist(ca_coords1, ca_coords1)
  # For each CA, check if any other CA is within EN distance range
  for i in range(len(protkeep1_indices)):
    # Check distances to all other CAs (excluding self)
    dists = ca_distances1[i]
    mask = (dists >= en_min) & (dists <= en_max)
    mask[i] = False  # Exclude self
    if np.any(mask):
      laterkeep1_resnames.add(prot1_resname[protkeep1_indices[i]])

laterkeep2_resnames = set()
if len(protkeep2_indices) > 1:
  ca_coords2 = prot2_coords[protkeep2_indices]
  ca_distances2 = cdist(ca_coords2, ca_coords2)
  for i in range(len(protkeep2_indices)):
    dists = ca_distances2[i]
    mask = (dists >= en_min) & (dists <= en_max)
    mask[i] = False
    if np.any(mask):
      laterkeep2_resnames.add(prot2_resname[protkeep2_indices[i]])

# Helper function to extract residue number from resname (e.g., "123ALA" -> 123, "123CLYS" -> 123)
def get_resnum(resname):
  # Extract leading digits to handle both 3-letter (ALA) and 4-letter (CLYS, NLYS) residue codes
  digits = ''
  for c in resname:
    if c.isdigit():
      digits += c
    else:
      break
  return int(digits)

def get_res3(resname):
  """Extract residue name from GRO resname field (e.g. '219ZN' -> 'ZN', '123ALA' -> 'ALA')."""
  for i, c in enumerate(resname):
    if not c.isdigit():
      return resname[i:]
  return resname

# Minimum fragment length (residues)
MIN_FRAGMENT_LEN = 5

def extend_small_fragments(kept_resnames, all_resnames):
  """Extend fragments smaller than MIN_FRAGMENT_LEN by adding neighboring residues."""
  if len(kept_resnames) == 0:
    return kept_resnames

  # Get unique residue numbers from kept resnames
  kept_resnums = sorted(set(get_resnum(rn) for rn in kept_resnames))

  # Get all available residue numbers from original protein
  all_resnums = sorted(set(get_resnum(rn) for rn in all_resnames))
  all_resnums_set = set(all_resnums)

  # Build mapping from resnum to resname (for adding back)
  resnum_to_resname = {}
  for rn in all_resnames:
    resnum = get_resnum(rn)
    if resnum not in resnum_to_resname:
      resnum_to_resname[resnum] = rn

  # Identify fragments (contiguous residue groups)
  fragments = []
  current_frag = [kept_resnums[0]]
  for i in range(1, len(kept_resnums)):
    if kept_resnums[i] == kept_resnums[i-1] + 1:
      current_frag.append(kept_resnums[i])
    else:
      fragments.append(current_frag)
      current_frag = [kept_resnums[i]]
  fragments.append(current_frag)

  # Extend small fragments
  extended_resnums = set(kept_resnums)
  for frag in fragments:
    if len(frag) < MIN_FRAGMENT_LEN:
      needed = MIN_FRAGMENT_LEN - len(frag)
      frag_start = frag[0]
      frag_end = frag[-1]

      # Try to extend in both directions alternately
      added = 0
      extend_before = 1
      extend_after = 1
      while added < needed:
        # Try extending before
        candidate = frag_start - extend_before
        if candidate in all_resnums_set and candidate not in extended_resnums:
          extended_resnums.add(candidate)
          added += 1
          extend_before += 1
          if added >= needed:
            break
        else:
          extend_before += 1

        # Try extending after
        candidate = frag_end + extend_after
        if candidate in all_resnums_set and candidate not in extended_resnums:
          extended_resnums.add(candidate)
          added += 1
          extend_after += 1
          if added >= needed:
            break
        else:
          extend_after += 1

        # Prevent infinite loop if no more residues available
        if extend_before > 100 and extend_after > 100:
          break

  # Convert back to resnames
  extended_resnames = set()
  for rn in all_resnames:
    if get_resnum(rn) in extended_resnums:
      extended_resnames.add(rn)

  return extended_resnames

def fill_small_gaps(kept_resnames, all_resnames, ter_pos, max_gap=3):
  """Fill gaps smaller than max_gap residues to avoid introducing artificial chain breaks.

  Never fills gaps that cross TER positions (different chain IDs).
  """
  if len(kept_resnames) == 0:
    return kept_resnames

  # Get sorted residue numbers
  kept_resnums = sorted(set(get_resnum(rn) for rn in kept_resnames))
  all_resnums = sorted(set(get_resnum(rn) for rn in all_resnames))
  all_resnums_set = set(all_resnums)

  # Build mapping from resnum to resname and res3
  resnum_to_resname = {}
  resnum_to_res3 = {}
  for rn in all_resnames:
    resnum = get_resnum(rn)
    res3 = get_res3(rn)
    if resnum not in resnum_to_resname:
      resnum_to_resname[resnum] = rn
      resnum_to_res3[resnum] = res3

  # Build set of residue numbers that have TER after them
  ter_resnums = set()
  for ter_resnum, ter_res3 in ter_pos:
    ter_resnums.add(ter_resnum)

  # Identify gaps and fill small ones (but not across TER positions)
  extended_resnums = set(kept_resnums)
  for i in range(len(kept_resnums) - 1):
    current_resnum = kept_resnums[i]
    next_resnum = kept_resnums[i + 1]
    gap = next_resnum - current_resnum - 1

    if 0 < gap <= max_gap:
      # Check if there's a TER position within this gap
      has_ter = False
      for check_resnum in range(current_resnum, next_resnum):
        if check_resnum in ter_resnums:
          # Verify the residue name matches (to avoid false positives)
          if check_resnum in resnum_to_res3:
            ter_res3 = resnum_to_res3[check_resnum]
            if (check_resnum, ter_res3) in ter_pos:
              has_ter = True
              break

      if has_ter:
        # Don't fill gaps across different chains (TER positions)
        continue

      # Fill this gap by adding missing residues
      print(f"Filling gap of {gap} residue(s) between {current_resnum} and {next_resnum}")
      for missing_resnum in range(current_resnum + 1, next_resnum):
        if missing_resnum in all_resnums_set:
          extended_resnums.add(missing_resnum)

  # Convert back to resnames
  filled_resnames = set()
  for rn in all_resnames:
    if get_resnum(rn) in extended_resnums:
      filled_resnames.add(rn)

  return filled_resnames

def remove_caps(kept_resnames):
  """Remove all ACE/NME cap residues from the cutout.

  The cutout should only contain real protein residues.
  cap_termini.py will add fresh caps where needed after the cutout is written.
  """
  cleaned_resnames = set()
  for rn in kept_resnames:
    res3 = get_res3(rn)
    if res3 not in ("ACE", "NME"):
      cleaned_resnames.add(rn)

  return cleaned_resnames

# Fill small gaps (< 4 residues) to avoid introducing artificial chain breaks
# Never fill across TER positions (different chain IDs)
laterkeep1_resnames = fill_small_gaps(laterkeep1_resnames, prot1_resname, ter_positions, max_gap=3)
laterkeep2_resnames = fill_small_gaps(laterkeep2_resnames, prot2_resname, ter_positions, max_gap=3)

# Extend small fragments by adding neighboring residues
laterkeep1_resnames = extend_small_fragments(laterkeep1_resnames, prot1_resname)
laterkeep2_resnames = extend_small_fragments(laterkeep2_resnames, prot2_resname)

# Remove all ACE/NME caps - cap_termini.py will add fresh ones to the cutout
laterkeep1_resnames = remove_caps(laterkeep1_resnames)
laterkeep2_resnames = remove_caps(laterkeep2_resnames)

# Add structural ions near the kept protein residues
# Ions are single-atom residues that should be included if within keepcutoff
# of any kept protein atom (they don't participate in fragment/gap logic)
def add_nearby_ions(kept_resnames, all_resnames, all_coords):
  """Add ion residues within keepcutoff of any kept protein atom."""
  if len(kept_resnames) == 0 or len(all_resnames) == 0:
    return kept_resnames

  # Separate kept protein atom indices and ion atom indices
  kept_indices = []
  ion_indices = []
  for i, rn in enumerate(all_resnames):
    res3 = rn[len(str(get_resnum(rn))):]  # extract residue name after digits
    if rn in kept_resnames:
      kept_indices.append(i)
    elif res3 in ION_RESIDUES:
      ion_indices.append(i)

  if not kept_indices or not ion_indices:
    return kept_resnames

  kept_coords = all_coords[kept_indices]
  ion_coords = all_coords[ion_indices]

  # Check distance from each ion to nearest kept atom
  dists = cdist(ion_coords, kept_coords)
  min_dists = np.min(dists, axis=1)

  added = set()
  for idx, ion_i in enumerate(ion_indices):
    if min_dists[idx] <= keepcutoff:
      added.add(all_resnames[ion_i])

  return kept_resnames | added

laterkeep1_resnames = add_nearby_ions(laterkeep1_resnames, prot1_resname, prot1_coords)
laterkeep2_resnames = add_nearby_ions(laterkeep2_resnames, prot2_resname, prot2_coords)

def clean_ter_positions(kept_resnames, ter_pos, real_breaks):
  """Remove TER positions that now fall between contiguous residues after extension.

  Never removes real chain breaks (TER between consecutively numbered residues
  in the source PDB), as these represent true physical breaks.
  """
  if len(kept_resnames) == 0:
    return ter_pos

  # Get sorted residue numbers and build resnum -> resname mapping
  resnum_to_res3 = {}
  for rn in kept_resnames:
    resnum = get_resnum(rn)
    res3 = get_res3(rn)
    resnum_to_res3[resnum] = res3

  resnums = sorted(resnum_to_res3.keys())

  # Check each TER position - remove if residues are now contiguous
  cleaned_ter_pos = set()
  removed_ters = []
  for ter_resnum, ter_res3 in ter_pos:
    # Never remove real chain breaks (physical breaks between consecutive residues)
    if (ter_resnum, ter_res3) in real_breaks:
      cleaned_ter_pos.add((ter_resnum, ter_res3))
      continue
    # Check if this TER position is followed by a contiguous residue
    if ter_resnum in resnums and (ter_resnum + 1) in resnums:
      # Verify the residue name matches
      if resnum_to_res3[ter_resnum] == ter_res3:
        # Gap was closed - don't keep this TER
        removed_ters.append((ter_resnum, ter_res3))
        continue
    cleaned_ter_pos.add((ter_resnum, ter_res3))

  if removed_ters:
    print(f"Removed {len(removed_ters)} TER position(s) where gaps were closed:")
    for ter_resnum, ter_res3 in sorted(removed_ters):
      print(f"  TER after {ter_resnum} {ter_res3}")

  return cleaned_ter_pos

# Clean up TER positions that may have been closed by extension
ter_positions = clean_ter_positions(laterkeep1_resnames, ter_positions, real_chain_breaks)
ter_positions = clean_ter_positions(laterkeep2_resnames, ter_positions, real_chain_breaks)

# Collect final atoms to keep
protlaterkeep1 = [(prot1_resname[i], prot1_atomname[i], prot1_coords[i])
                  for i in range(len1) if prot1_resname[i] in laterkeep1_resnames]
protlaterkeep2 = [(prot2_resname[i], prot2_atomname[i], prot2_coords[i])
                  for i in range(len2) if prot2_resname[i] in laterkeep2_resnames]

lenlk1 = len(protlaterkeep1)
lenlk2 = len(protlaterkeep2)

# Write cutout PDB file
with open("cutout.pdb", "w") as pdbfile:
  atom_num = 0
  prev_resnum = None
  prev_res3 = None

  # Write protein A atoms
  for i in range(lenlk1):
    resname, atomname, coords = protlaterkeep1[i]
    resnum = get_resnum(resname)
    res3 = get_res3(resname)

    # Write TER record if there's a gap in residue numbering
    # OR if residues are consecutive but TER existed in fixed.pdb (real chain break)
    if prev_resnum is not None:
      has_gap = resnum > prev_resnum + 1
      has_ter_in_fixed = (prev_resnum, prev_res3) in ter_positions and resnum == prev_resnum + 1
      if has_gap or has_ter_in_fixed:
        atom_num += 1
        pdbfile.write(f"TER  {atom_num:>6}       {' ':>2} A{prev_resnum:>4}\n")

    atom_num += 1
    pdbfile.write(f"ATOM {atom_num:>6}  {atomname:<3} {res3:>2} A{resnum:>4}    "
                  f"{coords[0]*10:8.3f}{coords[1]*10:8.3f}{coords[2]*10:8.3f}"
                  f"  1.00  0.00          {atomname[0]:>2}\n")
    prev_resnum = resnum
    prev_res3 = res3

  # Write TER between protein A and protein B
  if lenlk1 > 0 and lenlk2 > 0:
    atom_num += 1
    pdbfile.write(f"TER  {atom_num:>6}       {' ':>2} A{prev_resnum:>4}\n")

  prev_resnum = None
  prev_res3 = None

  # Write protein B atoms
  for i in range(lenlk2):
    resname, atomname, coords = protlaterkeep2[i]
    resnum = get_resnum(resname)
    res3 = get_res3(resname)

    # Write TER record if there's a gap in residue numbering
    # OR if residues are consecutive but TER existed in fixed.pdb (real chain break)
    if prev_resnum is not None:
      has_gap = resnum > prev_resnum + 1
      has_ter_in_fixed = (prev_resnum, prev_res3) in ter_positions and resnum == prev_resnum + 1
      if has_gap or has_ter_in_fixed:
        atom_num += 1
        pdbfile.write(f"TER  {atom_num:>6}       {' ':>2} B{prev_resnum:>4}\n")

    atom_num += 1
    pdbfile.write(f"ATOM {atom_num:>6}  {atomname:<3} {res3:>2} B{resnum:>4}    "
                  f"{coords[0]*10:8.3f}{coords[1]*10:8.3f}{coords[2]*10:8.3f}"
                  f"  1.00  0.00          {atomname[0]:>2}\n")
    prev_resnum = resnum
    prev_res3 = res3
