#!/usr/bin/env python3
#
# merge_ligand.py - Merge OpenFF-parametrized ligands into protein topology
#
# Inserts ligand ITP includes and coordinates into the protein topology and
# GRO file generated by pdb2gmx. Handles chain assignment for pulling.
#
# Usage: python merge_ligand.py -t topol.top -c conf.gro -m chain_map.gs
#

import os
import sys
import glob
import argparse

parser = argparse.ArgumentParser(description="Merge ligand topology and coordinates into protein system.")
parser.add_argument('-t', '--topol', type=str, default="topol.top", help="Protein topology file")
parser.add_argument('-c', '--conf', type=str, required=True, help="Protein coordinate file (GRO)")
parser.add_argument('-m', '--chainmap', type=str, required=True, help="Chain map file (chain_map.gs)")
args = parser.parse_args()

# Read ligand manifest (written by parametrize_ligand.py)
# Format: mol_name  itp_path  atomtypes_path  gro_path  natoms
manifest_path = os.path.join(os.path.dirname(args.chainmap), "ligand_manifest.gs")
if not os.path.isfile(manifest_path):
    # Fallback: try ligand_info.gs for backward compatibility
    ligand_info_path = os.path.join(os.path.dirname(args.chainmap), "ligand_info.gs")
    if not os.path.isfile(ligand_info_path):
        print("No ligand_manifest.gs or ligand_info.gs found, skipping ligand merge.")
        sys.exit(0)
    # Legacy mode: shared ITP per resname
    ligands = []
    with open(ligand_info_path) as f:
        for line in f:
            if line.strip().startswith("#") or not line.strip():
                continue
            parts = line.strip().split()
            if len(parts) >= 3:
                ligands.append((parts[0], parts[1], int(parts[2])))
    available_ligands = []
    for resname, chain, natoms in ligands:
        itp = f"ligand_{resname}.itp"
        gro = f"ligand_{resname}_{chain}.gro"
        if not os.path.isfile(gro):
            gro = f"ligand_{resname}.gro"
        atomtypes = f"ligand_{resname}_atomtypes.itp"
        if os.path.isfile(itp) and os.path.isfile(gro):
            available_ligands.append((resname, chain, natoms, itp, gro, atomtypes, atomtypes))
        else:
            print(f"Warning: {itp} or {gro} not found, skipping {resname} chain {chain}")
else:
    # New mode: per-instance ITP from manifest
    available_ligands = []
    # Also read ligand_info.gs for chain assignments (needed for proximity filtering)
    ligand_info_path = os.path.join(os.path.dirname(args.chainmap), "ligand_info.gs")
    chain_for_ligand = {}
    if os.path.isfile(ligand_info_path):
        idx = 0
        with open(ligand_info_path) as f:
            for line in f:
                if line.strip().startswith("#") or not line.strip():
                    continue
                parts = line.strip().split()
                if len(parts) >= 3:
                    chain_for_ligand[idx] = parts[1]
                    idx += 1

    with open(manifest_path) as f:
        for idx, line in enumerate(f):
            if line.strip().startswith("#") or not line.strip():
                continue
            parts = line.strip().split()
            if len(parts) >= 5:
                mol_name, itp, atomtypes, gro = parts[0], parts[1], parts[2], parts[3]
                natoms = int(parts[4])
                chain = chain_for_ligand.get(idx, "")
                if os.path.isfile(itp) and os.path.isfile(gro):
                    available_ligands.append((mol_name, chain, natoms, itp, gro, atomtypes))
                else:
                    print(f"Warning: {itp} or {gro} not found, skipping {mol_name}")

if not available_ligands:
    print("No parametrized ligands found, skipping merge.")
    sys.exit(0)

# Filter ligands by proximity to existing protein atoms (skip distant buffer molecules)
import numpy as np
from scipy.spatial.distance import cdist

LIGAND_PROXIMITY_CUTOFF = 0.5  # nm — any ligand atom must be within this distance of a protein atom

def read_gro_coords(path, max_atoms=None):
    """Read coordinates from GRO file using fixed-width format (positions 20-44)."""
    coords = []
    with open(path) as f:
        lines = f.readlines()
    n = int(lines[1].strip())
    if max_atoms:
        n = min(n, max_atoms)
    for line in lines[2:2 + n]:
        try:
            x = float(line[20:28])
            y = float(line[28:36])
            z = float(line[36:44])
            coords.append((x, y, z))
        except (ValueError, IndexError):
            pass
    return coords

prot_coords = read_gro_coords(args.conf)

if prot_coords:
    prot_arr = np.array(prot_coords)
    filtered = []
    for resname, chain, natoms, itp, gro, atomtypes in available_ligands:
        lig_coords = read_gro_coords(gro)
        if lig_coords:
            dists = cdist(np.array(lig_coords), prot_arr)
            min_dist = dists.min()
            if min_dist <= LIGAND_PROXIMITY_CUTOFF:
                filtered.append((resname, chain, natoms, itp, gro, atomtypes))
            else:
                print(f"Skipping {resname} chain {chain}: nearest protein atom {min_dist:.2f} nm (> {LIGAND_PROXIMITY_CUTOFF} nm)")
        else:
            filtered.append((resname, chain, natoms, itp, gro, atomtypes))
    available_ligands = filtered

if not available_ligands:
    print("No ligands within proximity cutoff, skipping merge.")
    sys.exit(0)

# Sort by resname so all instances of the same molecule type are contiguous
# (GROMACS requires molecules in GRO to match [ molecules ] order in topology)
available_ligands.sort(key=lambda x: x[0])

# Read chain_map.gs to determine protein B residue numbers
residues_b = set()
with open(args.chainmap) as f:
    for line in f:
        if not line.strip().startswith("#"):
            try:
                residues_b.add(int(line.strip()))
            except (ValueError, IndexError):
                pass

# Read protein B chains from chain_map header or sp.gs
# We need to know which chain IDs belong to protein B
# Read from the header comment in chain_map.gs
chains_b = set()
with open(args.chainmap) as f:
    for line in f:
        if "chain(s):" in line:
            chain_str = line.split("chain(s):")[1].strip()
            chains_b = set(c.strip() for c in chain_str.split(","))
            break

# ---- Merge topology ----
with open(args.topol) as f:
    topol_content = f.read()

# Find insertion points
# 1. Insert #include for ligand ITP after the forcefield include
#    (after the first #include line)
lines = topol_content.split("\n")
insert_include_idx = None
for i, line in enumerate(lines):
    if line.strip().startswith("#include") and "forcefield" in line:
        insert_include_idx = i + 1
        break

if insert_include_idx is None:
    # Fallback: insert at the beginning
    insert_include_idx = 0

# 2. Insert ligand molecule counts in [ molecules ] section
molecules_idx = None
for i, line in enumerate(lines):
    if line.strip() == "[ molecules ]":
        molecules_idx = i
        break

# Find where moleculetype sections start (for inserting moleculetype includes)
first_moltype_idx = None
for i, line in enumerate(lines):
    if line.strip().startswith("#include") and "topol_" in line:
        first_moltype_idx = i
        break

if first_moltype_idx is None:
    first_moltype_idx = insert_include_idx + 1

# Build the new topology
# Atomtypes must come BEFORE any moleculetype (GROMACS requirement)
# So: forcefield.itp → atomtypes includes → protein moleculetype includes → ligand moleculetype includes
new_lines = []
includes_added = set()
for i, line in enumerate(lines):
    # Before the first protein moleculetype include, insert ligand moleculetype includes
    if i == first_moltype_idx:
        for resname, chain, natoms, itp, gro, atomtypes in available_ligands:
            if itp not in includes_added:
                new_lines.append(f'#include "{itp}"')
                includes_added.add(itp)
    new_lines.append(line)
    # After forcefield include, add ligand atomtype includes
    if i == insert_include_idx:
        atomtypes_added = set()
        for resname, chain, natoms, itp, gro, atomtypes in available_ligands:
            if atomtypes not in atomtypes_added and os.path.isfile(atomtypes):
                new_lines.append(f'#include "{atomtypes}"')
                atomtypes_added.add(atomtypes)

# Add ligand molecules to [ molecules ] section
# Find the last line of [ molecules ] (before any intermolecular_interactions or EOF)
final_lines = []
mol_section_end = None
in_molecules = False
for i, line in enumerate(new_lines):
    if "[ molecules ]" in line:
        in_molecules = True
    elif in_molecules and line.strip().startswith("["):
        in_molecules = False
        mol_section_end = i
    elif in_molecules and line.strip().startswith(";"):
        # Skip comments, but this might be where we insert
        if mol_section_end is None:
            mol_section_end = None  # keep looking

# Find actual end of molecules entries
for i in range(len(new_lines) - 1, -1, -1):
    line = new_lines[i].strip()
    if line and not line.startswith(";") and not line.startswith("[") and not line.startswith("#"):
        # This is the last molecule entry
        mol_insert_idx = i + 1
        break

# Insert ligand molecule entries (each instance is its own molecule type)
ligand_mol_lines = []
for resname, chain, natoms, itp, gro, atomtypes in available_ligands:
    ligand_mol_lines.append(f"{resname:20s} 1")

# Rebuild with ligand molecules inserted
output_lines = new_lines[:mol_insert_idx] + ligand_mol_lines + new_lines[mol_insert_idx:]

with open(args.topol, "w") as f:
    f.write("\n".join(output_lines))

print(f"Updated {args.topol}: added {len(includes_added)} ligand ITP include(s) and {len(ligand_mol_lines)} molecule entry/entries")

# ---- Merge coordinates ----
with open(args.conf) as f:
    gro_lines = f.readlines()

# GRO format: line 1 = title, line 2 = natoms, lines 3..n+2 = atoms, last line = box
title = gro_lines[0]
n_protein_atoms = int(gro_lines[1].strip())
protein_atoms = gro_lines[2:2 + n_protein_atoms]
box_line = gro_lines[2 + n_protein_atoms]

# Read ligand coordinates and append
ligand_atom_lines = []
next_resnum = 1  # Will be set properly
# Find the highest residue number in the protein GRO
import re
max_resnum = 0
for line in protein_atoms:
    m = re.match(r"\s*(\d+)", line)
    if m:
        resnum = int(m.group(1))
        if resnum > max_resnum:
            max_resnum = resnum

next_resnum = max_resnum + 1
next_atomnum = n_protein_atoms + 1
ligand_resnum_map = {}  # resname -> new_resnum (for chain_map update)

for resname, chain, natoms, itp, gro, atomtypes in available_ligands:
    with open(gro) as f:
        lig_gro_lines = f.readlines()

    n_lig_atoms = int(lig_gro_lines[1].strip())

    for line in lig_gro_lines[2:2 + n_lig_atoms]:
        # Rewrite residue number and atom number
        # GRO format: %5d%-5s%5s%5d%8.3f%8.3f%8.3f
        # First 5 chars: residue number, next 5: residue name, next 5: atom name, next 5: atom number
        old_content = line.rstrip("\n")
        if len(old_content) < 44:
            continue

        # Extract atom name and coordinates (keep as-is)
        atom_name = old_content[10:15]
        coords_and_vel = old_content[20:]  # everything from coordinates onwards

        new_line = f"{next_resnum:5d}{resname:>5s}{atom_name}{next_atomnum:5d}{coords_and_vel}\n"
        ligand_atom_lines.append(new_line)
        next_atomnum += 1

    ligand_resnum_map[(resname, chain)] = next_resnum
    next_resnum += 1

# Write updated GRO
total_atoms = n_protein_atoms + len(ligand_atom_lines)
with open(args.conf, "w") as f:
    f.write(title)
    f.write(f"{total_atoms:5d}\n")
    for line in protein_atoms:
        f.write(line)
    for line in ligand_atom_lines:
        f.write(line)
    f.write(box_line)

print(f"Updated {args.conf}: {n_protein_atoms} protein + {len(ligand_atom_lines)} ligand = {total_atoms} total atoms")

# ---- Update chain_map.gs if ligand belongs to protein B ----
new_b_resnums = []
for (resname, chain), new_resnum in ligand_resnum_map.items():
    if chain in chains_b:
        new_b_resnums.append(new_resnum)
        print(f"Ligand {resname} (chain {chain}) assigned to protein B, resnum {new_resnum}")

if new_b_resnums:
    with open(args.chainmap, "a") as f:
        for resnum in new_b_resnums:
            f.write(f"{resnum}\n")

# ---- Write ligand_residues.gs for make_disres_en.py ----
lig_res_path = os.path.join(os.path.dirname(args.chainmap), "ligand_residues.gs")
with open(lig_res_path, "w") as f:
    f.write("# Residue numbers of parametrized ligands\n")
    for (resname, chain), new_resnum in ligand_resnum_map.items():
        f.write(f"{new_resnum}\n")

print(f"Wrote {lig_res_path}")
